### PR TITLE
The elevation field is 2 bytes, not 8.

### PR DESCRIPTION
**Pull request by ghost**
I believe the elevation message is just a single uint16_t field, which should be 2 bytes and not 8.

### CODE REVIEW

**Review by joshwardell — CHANGES_REQUESTED** [review]
Nice find. Old signal I haven't looked at in a while. Looks like it's actually 14 bit as well.
BO_ 984 ID3D8Elevation: 2 VehicleBus
 SG_ Elevation3D8 : 0|14@1- (1,0) [-8192|8191] "M"  Receiver

**Comment by ghost** [comment]
> Nice find. Old signal I haven't looked at in a while. Looks like it's actually 14 bit as well.

I'm seeing it listed as 16 bits in the "Model 3 CAN bus IDs and data" spreadsheet (https://docs.google.com/spreadsheets/d/1ijvNE4lU9Xoruvcg5AhUNLKr7xYyHcxa8YSkTxAERUw/edit#gid=0).

**Comment by joshwardell** [comment]
> I'm seeing it listed as 16 bits in the "Model 3 CAN bus IDs and data" spreadsheet (https://docs.google.com/spreadsheets/d/1ijvNE4lU9Xoruvcg5AhUNLKr7xYyHcxa8YSkTxAERUw/edit#gid=0).

Yeah, I am way behind at updating that spreadsheet. Wish there was a way to automate it

**Comment by ghost** [comment]
Oh, thanks. Where do you get the data for the spreadsheet - i.e. how do you know the field is 14 bits?

**Comment by joshwardell** [comment]
You just have to drive below sea level and see it go negative
I added this to the release I made

**Pull request closed without merging**
